figure(1)
subplot(7,1,1)
plot(Signal_Diagnostic(:,1))
title('Rolling Alive Signal Valid (0-Invalid, 1-Valid)')
subplot(7,1,2)
plot(Signal_Diagnostic(:,2))
title('CAN Transmission Valid (0-Invalid, 1-Valid)')
subplot(7,1,3)
plot(Signal_Diagnostic(:,3))
title('Hardware Status Valid (0-Invalid, 1-Valid)')
subplot(7,1,4)
plot(Signal_Diagnostic(:,4))
title('Mechanical Status Valid (0-Invalid, 1-Valid)')
subplot(7,1,5)
plot(Signal_Diagnostic(:,8))
title('Pressure Signal Valid (0-Invalid, 1-Valid)')
subplot(7,1,6)
plot(Signal_Diagnostic(:,9))
title('Position Signal Valid (0-Invalid, 1-Valid)')
subplot(7,1,7)
plot(Signal_Diagnostic(:,10))
title('Mode Status Valid (0-Invalid, 1-Valid)')

figure(2)
subplot(3,1,1)
plot(Signal_Diagnostic(:,5))
title('Temp Warning Flag')
subplot(3,1,2)
plot(Signal_Diagnostic(:,6))
title('Temp Error Flag')
subplot(3,1,3)
plot(Signal_Diagnostic(:,7))
title('Battery Voltage Flag')

figure(3)
plot(Clutch_Status)
ylabel('0 - Invalid, 1 - Valid')
title('Component Status Assessment')
xlabel('Time')



